excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://bendavis20.github.io
title: Pistachio war
email: 
author: bendavis20
description: Pistachios
paginate: 1
google_analytics: 